# Generated by Django 4.1.2 on 2022-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product_category',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('art', 'Art'), ('bags', 'Bags'), ('books', 'Books'), ('cameras', 'Cameras'), ('cell phone accessories', 'Cell Phone Accessories'), ('cell phones', 'Cell Phones'), ('clothes', 'Clothes'), ('computers', 'Computers'), ('cosmetics', 'Cosmetics'), ('jewelry', 'Jewelry'), ('musical instruments', 'Musical Instruments'), ('sporting goods', 'Sporting Goods'), ('shoes', 'Shoes'), ('toys', 'Toys'), ('watches', 'Watches'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
